DATALOADER:
  BATCH_SIZE: 64
  NUM_INSTANCES: 4
  NUM_WORKERS: 4
DATASETS:
  NAME: Market1501
  ROOT: /home/hzh/data
DEVICE: cuda
DEVICE_ID: 1
INPUT:
  HF_PROB: 0.5
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  ARCH: resnet50
  NAME: baseline
  STRIDE: 2
OUTPUT_DIR: ./checkpoint/DogCat/Exp-1
SCHEDULER:
  GAMMA: 0.5
  NAME: StepLR
  STEP: 10
SOLVER:
  BASE_LR: 0.001
  CHECK_PERIOD: 5
  EVAL_PERIOD: 1
  LOSS: softmax_triplet
  MARGIN: 0.3
  MAX_EPOCHS: 320
  MOMENTUM: 0.9
  NESTEROV: True
  OPTIMIZER_NAME: SGD
  PRINT_FREQ: 10
  WEIGHT_DECAY: 0.0005
TEST:
  BATCH_SIZE: 128
