OUTPUT_DIR: "./checkpoint/DogCat/Exp-1"
DEVICE: "cuda"
DEVICE_ID: ('1,2,3')

MODEL:
  NAME: 'ResModel'
  BACKBONE: 'ResNet50'
  PRETRAINED: True

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  HF_PROB: 0.5 # random horizontal flip

DATASETS:
  NAME: 'Market1501'
  ROOT: '/home/hzh/data'

DATALOADER:
  NUM_WORKERS: 2
  BATCH_SIZE: 64
  NUM_INSTANCES: 16

SOLVER:
  LOSS: 'softmax'
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 320
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.0005

  CHECK_PERIOD: 5
  EVAL_PERIOD: 1
  PRINT_FREQ: 10

SCHEDULER:
  NAME: 'StepLR'
  STEP: 2
  GAMMA: 0.5

TEST:
  BATCH_SIZE: 128


