OUTPUT_DIR: "./checkpoint/Market1501/Exp-1"
DEVICE: "cuda"
DEVICE_ID: ('1,2')

MODEL:
  NAME: 'baseline'
  ARCH: 'resnet50'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  HF_PROB: 0.5 # random horizontal flip

DATASETS:
  NAME: 'Market1501'
  ROOT: '/home/hzh/data'

DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE: 128
  NUM_INSTANCES: 4

SOLVER:
  LOSS: 'softmax_triplet'
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 320
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005

  CHECK_PERIOD: 5
  EVAL_PERIOD: 1
  PRINT_FREQ: 10

SCHEDULER:
  NAME: 'StepLR'
  STEP: 10
  GAMMA: 0.5

TEST:
  BATCH_SIZE: 128


