OUTPUT_DIR: "./checkpoint/CUHK01/Exp-1011-2-finetune-2"
DEVICE: "cuda"
DEVICE_ID: ('2')

MODEL:
  NAME: 'baseline'
  ARCH: 'resnet50'
  LABEL_SMOOTH: True

INPUT:
  SIZE_TRAIN: [384, 128]

DATASETS:
  NAME: 'CUHK01'
  ROOT: '/home/hzh/data'

DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE: 64
  NUM_INSTANCES: 4

SOLVER:
  LOSS: 'softmax_triplet'
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 60
  BASE_LR: 0.0004
  WEIGHT_DECAY: 0.0005

  EVAL_PERIOD: 5
  PRINT_FREQ: 10

SCHEDULER:
  NAME: 'WarmupStepLR'
  STEP: 20
  GAMMA: 0.1

  WARMUP_FACTOR: 100
  WARMUP_ITERS: 20


TEST:
  BATCH_SIZE: 64


